# Generated by Django 4.2.6 on 2024-06-07 22:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glasses',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
