# Generated by Django 4.2.6 on 2024-06-09 01:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0002_glasses_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glasses',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
