FROM python:3.9-slim

RUN apt-get update \
    && apt-get install -y \
        libgl1-mesa-glx \
        libglfw3 \
        mesa-utils \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python manage.py collectstatic --noinput

EXPOSE 8000


CMD ["gunicorn", "MentorM.wsgi:application", "--bind", "0.0.0.0:8000"]