[phases.setup]
aptPackages = [
  "build-essential",
  "cmake",
  "libssl-dev",
  "libffi-dev",
  "zlib1g-dev",
  "gcc",
  "g++",
  "libc6-dev"
]

[packages]
wheel = { version = "latest" }
cmake = { version = "3.21.1" }
gxx = { version = "9" }

[phases.build]
commands = [
  "pip install --upgrade pip",
  "pip install --upgrade setuptools",
  "pip install --upgrade wheel",
  "cmake --version",
  "gcc --version",
  "g++ --version",
  "pip install dlib --use-pep517"
]