[phases.setup]
aptPackages = [
  "build-essential",
  "cmake",
  "libssl-dev",
  "libffi-dev",
  "zlib1g-dev",
  "gcc",
  "g++",
  "libc6-dev"
]

[packages]
cmake = { version = "3.21.1" }
gxx = { version = "9" }
glibc = { version = "2.36" }
