[phases.setup]
nixPkgs = [
  "python38",
  "python38Packages.pip",
  "python38Packages.setuptools",
  "python38Packages.wheel",
  "cmake",
  "gcc",
  "gcc11",
  "libffi",
  "zlib",
  "libjpeg",
  "libpng",
  "glibc"
]

[phases.build]
commands = [
  "pip install --upgrade pip",
  "pip install --upgrade setuptools",
  "pip install --upgrade wheel",
  "cmake --version",
  "gcc --version",
  "g++ --version",
  "pip install dlib --use-pep517"
]