[phases.setup]
nixPkgs = [
  "python38",
  "python38Packages.pip",
  "python38Packages.setuptools",
  "python38Packages.wheel",
  "cmake",
  "gcc11",
  "libffi",
  "zlib",
  "libjpeg",
  "libpng",
  "glibc"
]
