# Generated by Django 4.2.6 on 2024-06-24 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Haircuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(upload_to='haircuts/', verbose_name='Imagenes')),
                ('Corte', models.CharField(max_length=30, verbose_name='Cortes')),
                ('face_shape', models.CharField(choices=[('ovalado', 'Ovalado'), ('cuadrado', 'Cuadrado'), ('redondo', 'Redondo'), ('corazon', 'Corazón'), ('diamante', 'Diamante')], max_length=20)),
                ('race', models.CharField(choices=[('normal', 'Normal'), ('black', 'Negro')], default='normal', max_length=20)),
                ('gender', models.CharField(choices=[('Man', 'Masculino'), ('Woman', 'Femenino')], default='Man', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserHaircuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('haircut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haircut.haircuts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
