# Generated by Django 4.2.6 on 2024-06-07 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Haircuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(upload_to='haircuts/', verbose_name='Imagenes')),
                ('Corte', models.CharField(max_length=30, verbose_name='Cortes')),
                ('face_shape', models.CharField(choices=[('ovalado', 'Ovalado'), ('cuadrado', 'Cuadrado'), ('redondo', 'Redondo'), ('corazon', 'Corazón')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserHaircuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha de realización', models.DateField(auto_now_add=True, verbose_name='Fechas de realización')),
                ('haircut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haircut.haircuts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
