# Generated by Django 5.0.6 on 2024-07-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haircuts',
            name='face_shape',
            field=models.CharField(choices=[('ovalado', 'Ovalado'), ('cuadrado', 'Cuadrado'), ('redondo', 'Redondo'), ('corazon', 'Corazón'), ('oblongo', 'Oblongo')], max_length=20),
        ),
    ]
