# Generated by Django 4.2.6 on 2024-06-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircut', '0002_haircuts_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='haircuts',
            name='race',
            field=models.CharField(choices=[('normal', 'Normal'), ('negro', 'Negro')], default='normal', max_length=20),
        ),
    ]
