# Generated by Django 4.2.6 on 2024-06-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircut', '0003_haircuts_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haircuts',
            name='race',
            field=models.CharField(choices=[('normal', 'Normal'), ('negro', 'Negro')], default=('normal', 'Normal'), max_length=20),
        ),
    ]
