# Generated by Django 4.2.6 on 2024-06-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircut', '0005_alter_haircuts_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='haircuts',
            name='gender',
            field=models.CharField(choices=[('Man', 'Masculino'), ('Woman', 'Femenino')], default='Man', max_length=20),
        ),
        migrations.AlterField(
            model_name='haircuts',
            name='race',
            field=models.CharField(choices=[('normal', 'Normal'), ('black', 'Negro')], default='normal', max_length=20),
        ),
    ]
