# Generated by Django 4.2.6 on 2024-06-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircut', '0006_haircuts_gender_alter_haircuts_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haircuts',
            name='face_shape',
            field=models.CharField(choices=[('ovalado', 'Ovalado'), ('cuadrado', 'Cuadrado'), ('redondo', 'Redondo'), ('corazon', 'Corazón'), ('diamante', 'Diamante')], max_length=20),
        ),
    ]
